src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    const HEAT = [
        0 => 'Électrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column (type="string", length=255)
     */
    private $filename;


    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="5", max="40")
     */
    private $title;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min="10", max="400")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @var
     */
    private $slug;


    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     */
    public function setFilename(?string $filename): void
    {
        $this->filename = $filename;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     */
    public function setImageFile(?File $imageFile): void
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
    }

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     *
     */
    public function getFormattedPrice()
    {
        return number_format($this->price, 0,'',' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('adress')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'form'
        ]);
    }

    /**
     * @return array
     */
    private function getChoices()
    {
        $choices = Property::HEAT;
        $outpout = [];
        foreach ($choices as $k => $v) {
            $outpout[$v] = $k;
        }
        return $outpout;
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearcher;
use App\Form\ContactType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Cocur\Slugify\Slugify;

class PropertyController extends AbstractController
{
    /**
     * @Route("/biens", name="properties")
     * @param PropertyRepository $propertyRepository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index (PropertyRepository $propertyRepository, PaginatorInterface $paginator, Request $request) : Response
    {
        // Gerer le traitement du formulaire de filtrage

        $search = new PropertySearcher();
        $form = $this->createForm(ContactType::class, $search);
        $form->handleRequest($request);


        $em = $this->getDoctrine()->getManager();

        // Gérer la pagination

        $properties = $paginator->paginate(
            $properties = $propertyRepository->findAllVisibleQuery($search),
            $request->query->getInt('page',1),12
        );

        return new Response($this->render('property/index.html.twig', [
            'current_menu' => 'properties',
                'properties' => $properties,
                'form' => $form->createView()
            ]
        ));
    }

    /**
     * @Route("/biens/{slug}-{id}", name="show", requirements={"slug": "[a-z0-9\-]*"})
     * @param PropertyRepository $propertyRepository
     * @param Property $property
     * @param string $slug
     * @param $id
     * @param Request $request
     * @param ContactNotification $notification
     * @return Response
     */
    public function show(PropertyRepository $propertyRepository, Property $property, string $slug, $id, Request $request, ContactNotification $notification): Response
    {
        // Mise en place des slugs

        if($property->getSlug() !== $slug)
        {
            return $this->redirectToRoute('show',[
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        ///////// Import Contact et Form de Contact //////////////

        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);
            $this->addFlash('success', 'Votre email a bien été envoyé');
            return $this->redirectToRoute('show', [
               'id' => $property->getId(),
               'slug' => $property->getSlug()
            ]);
        }

        $em = $this->getDoctrine()->getManager();
        $property = $propertyRepository->find($id);
        return $this->render('property/show.html.twig', [
            'property'=>$property,
            'current_menu' => 'properties',
            'form' => $form->createView()
        ]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
    {% if property.filename %}
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
        {% else %}
            <img src="{{ '/images/properties/default.jpeg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('show', {slug: property.slug, id: property.id}) }}">
                {{ property.title }}
            </a>
        </h5>
        <p class="card-text">{{ property.surface }} m² - {{ property.city }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold" >{{ property.formattedPrice }} €</div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title  %}Tous nos biens{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                {{ form_start(form) }}
                <div class="form-row align-items-end">
                    <div class="col">
                        {{ form_row(form.minSurface) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.maxPrice) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.options) }}
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <button class="btn btn-primary">Rechercher</button>
                        </div>
                    </div>
                </div>
                {{ form_end(form) }}
            </div>

        </div>
    </div>
    <div class="container mt-4">
        <h1>Voir tous mes biens</h1>
       <div class="row">
           {% for property in properties %}
               <div class="col-md-4">
                   {% include 'property/_property.html.twig' %}
               </div>
           {% endfor %}
       </div>
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ property.title }}{% endblock %}

{% block body %}
        <div class="jumbotron">
            <div class="container">

                {%  for message in app.flashes('success') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}

                {% if not form.vars.valid %}
                    <div class="alert alert-danger">
                        "Vos saisies sont invalides"
                    </div>
                {% endif %}


                <div class="row">
                    <div class="col-md-8">
                        {% if property.filename %}
                            <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto">
                        {% else %}
                            <img src="{{ '/images/properties/default.jpeg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
                        {% endif %}
                    </div>
                    <div class="col-md-4">
                        <h1>{{ property.title }}</h1>
                        <h2>{{ property.rooms }} pièces . {{  property.surface }} m²</h2>
                        <div class="text-primary" style="font-weight: bold; font-size: 4rem">{{ property.formattedPrice }} €</div>
                        <a href="#" class="btn btn-primary">Contacter l'agence</a>
                        <div id="contactForm" class="mt-4">
                            {{ form_start(form) }}
                            <div class="row">
                                <div class="col">{{ form_row(form.firstname) }}</div>
                                <div class="col">{{ form_row(form.lastname) }}</div>
                            </div>
                            <div class="row">
                                <div class="col">{{ form_row(form.phone) }}</div>
                                <div class="col">{{ form_row(form.email) }}</div>
                            </div>
                            {{ form_rest(form) }}
                            <div class="form-group">
                                <button class="btn btn-primary">Envoyer</button>
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
                <p class="jumbotron jumbotron-fluid mt-4">
                    {{ property.description | nl2br }}
                </p>
            </div>
        </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-stripped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }}</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Étage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                    <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}